### ISSUE TITLE
Auto update keeps running in background.

### ISSUE THREAD

**Issue by dozer47528** [deanishe/alfred-workflow#111] opened 2017-03-29 09:37 UTC
This is my project: [https://github.com/dozer47528/alfred2-hasher](https://github.com/dozer47528/alfred2-hasher)

The auto update thread keeps running and the CPU usage is very high.

![screen shot 2017-03-29 at 17 30 03](https://cloud.githubusercontent.com/assets/1676951/24448040/798a86d2-14a5-11e7-9c17-28a30fdfe92b.png)
![screen shot 2017-03-29 at 17 30 13](https://cloud.githubusercontent.com/assets/1676951/24448047/7c777760-14a5-11e7-8472-96c633a2176f.png)

**Comment by deanishe** [comment] 2017-03-29 11:54
What version of OSX & Alfred do you have?

This appears to be related to similar issues with other workflows, but I haven't been able to replicate the problem here.

**Comment by dozer47528** [comment] 2017-03-30 04:12
macOS Sierra 10.12.4
Alfred 3.3.1

**Comment by idpaterson** [comment] 2017-03-30 12:55
Same versions here but I'm not having any luck reproducing that with the hasher workflow even messing with the update-related cpickle files. Is this an occasional problem or does it get stuck every time you execute the workflow?

I don't know if my reported issue [Python hits 100% CPU](https://github.com/idpaterson/alfred-wunderlist-workflow/issues/147) is related or if the user was just seeing my workflow synchronizing their data. At least in my experience the workflow's sync is not CPU-bound since the API that I have to use is so slow... I was not able to get any further info from the user and have not seen it happen myself but will be watching this issue just in case.

**Comment by StartEnd** [comment] 2017-03-31 01:24
I have the same problem
macOS Sierra 10.12.4
Alfred 3.3.1

![](http://pizisong.qiniudn.com/2017-03-31-14909232135573.jpg)

![](http://pizisong.qiniudn.com/2017-03-31-14909232530969.jpg)

**Comment by deanishe** [comment] 2017-03-31 12:04
Definitely an issue with Sierra and the background code.

I'm not sure how much I can do about it, as I can't install Sierra and see the problem for myself.

**Comment by idpaterson** [comment] 2017-03-31 13:27
@StartEnd thanks for posting here. I was just able to get the 100% CPU issue here after a few tries with @dozer47528's workflow. @deanishe I'll take a look at this and @StartEnd if I find anything I'll give you a preview build of the Wunderlist workflow to test.

**Comment by idpaterson** [comment] 2017-03-31 16:09
Very interesting. To help isolate the problem here after a lot of debugging I changed the background script from 
```
cmd = ['/usr/bin/python', update_script, 'check', github_slug,
                   version]
```
to 
```
cmd = ['/usr/bin/perl', '-e', 'print 0']
```

The completely innocuous perl process hangs in exactly the same way. Does this give anyone any ideas?
![perl](https://cloud.githubusercontent.com/assets/507058/24558881/b7a73f3a-160a-11e7-98fe-ea43438829a0.png)

**Comment by idpaterson** [comment] 2017-03-31 16:31
This problem is resolved if only a single fork is performed for backgrounding, but that could introduce other issues. @deanishe is that worth considering as a workaround or does it at least better point to the root issue?

**Comment by idpaterson** [comment] 2017-03-31 16:55
Quite possibly a better workaround, the problem is resolved if the intermediary parent is not killed immediately. Adding a delay of 250ms (chosen arbitrarily) allows the subprocess call to run without hanging. I am not sure whether this has the possibility of introducing similar problems as forking only once.
```python
    # Do second fork.
    try:
        pid = os.fork()
        if pid > 0:
            time.sleep(0.25)
            sys.exit(0)  # Exit second parent.
```

**Comment by janclarin** [comment] 2017-03-31 18:02
I have the same problem, it's drained by battery on a few occasions now. I'm also on macOS 10.12.4 and Alfred 3.3.1. This occurred today with the alfred-wunderlist-workflow and also in my [workflow](https://github.com/janclarin/jisho-alfred-workflow).

**Comment by idpaterson** [comment] 2017-03-31 18:05
I'm going to move forward with a pull request based on the delayed parent process exit in case that ends up being the best solution and will publish a corresponding beta version of the Wunderlist workflow over in idpaterson/alfred-wunderlist-workflow/issues/147

**Comment by deanishe** [comment] 2017-03-31 18:22
Thanks, @idpaterson. Adding a delay isn't ideal, but it shouldn't be a big issue in the second fork.

**Comment by idpaterson** [comment] 2017-03-31 18:57
Unfortunately after more testing, the delay (even a longer delay) is not stopping the hung process which unless anyone has better ideas puts me back to forking only once which does reliably avoid the hung process.

**Comment by deanishe** [comment] 2017-03-31 19:18
May be a bug in my backgrounding code.

Perhaps you could try replacing my daemon code with [python-daemon](https://pypi.python.org/pypi/python-daemon/)? Flush standard streams before disconnecting from them? Pass `close_fds` to `subprocess.call()`?

**Comment by idpaterson** [comment] 2017-03-31 21:05
Thanks! No luck so far, but I have a bit more to try still just ran out of time for today. I had not noticed before but this is repeatable just running the background.py script in a terminal which eliminates any strange behavior from Alfred.

To test, I am running the following from within the cache directory using the hasher workflow (any with alfred-workflow will work). Here is the argcache file that I am using based on the simple perl print 0 script [__workflow_update_check.argcache.txt](https://github.com/deanishe/alfred-workflow/files/886786/__workflow_update_check.argcache.txt). About 70% of the time for me after running, perl is hung at 100% cpu.
```
cp __workflow_update_check.argcache.txt __workflow_update_check.argcache
alfred_version=3.3.1 /usr/bin/python /Volumes/Macintosh\ HD\ 2/OneDrive/Configs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.61DF0517-BCF1-4BE4-A240-06B7BF49F8A9/workflow/background.py  __workflow_update_check
```

I am also trying to create a minimal case that will reproduce this behavior but have not had any luck. I have not been able to get it to happen directly under python-daemon but can't identify any significant difference. Slicing and dicing the background script to bare minimum it's still hanging; I'm missing something.

**Comment by deanishe** [comment] 2017-03-31 21:33
Thanks very much for trying. I'll try and get some time with a Sierra machine this weekend and have a look myself.

**Comment by deanishe** [comment] 2017-04-01 15:27
Should be fixed in [v1.25](https://github.com/deanishe/alfred-workflow/releases/tag/v1.25)

Essentially, I replaced `sys.exit(0)` with `os._exit(0)` in the forking code. The old code was hanging left, right and centre, but I couldn't get the new code to hang on a Sierra machine.

Fingers crossed…

**Closed by deanishe** 2017-04-01 15:27 UTC

**Comment by vitorgalvao** [comment] 2017-04-01 15:31
Does `alfred-workflow` update itself as well, or is that something Workflow developers will have to do?

I’m guessing the latter, but wanted to confirm.

**Comment by deanishe** [comment] 2017-04-01 15:54
Nope. It can only fetch .alfredworkflow/.alfred3workflow files from GitHub releases and ask Alfred to install them.

Annoyingly, this bug affects the update mechanism, so a lot of folks might have to update by hand 😞

**Comment by deanishe** [comment] 2017-04-01 17:34
FWIW, Alfred-Workflow is on [the Cheeseshop](https://pypi.python.org/pypi/Alfred-Workflow/1.25), so upgrading is as simple as `pip install --target . --upgrade Alfred-Workflow`.

**Comment by idpaterson** [comment] 2017-04-01 17:47
Since the process does not freeze 100% of the time (at least for me) I did get an update prompt in my workflow when the new version was published and was able to install it after a few tries, but YMMV.

**Comment by deanishe** [comment] 2017-04-01 20:24
Yeah, you should be able to get the workflow to update quickly enough if you kill the rogue process a few times, but that takes some technical chops versus downloading the new version manually.

The Packal updater doesn't work on Alfred 3, either, and the next best help, [my Packal search workflow](https://github.com/deanishe/alfred-packal-search) is buggy, too 😒 

Which reminds me … I have to upload my updated workflows to Packal, too.

I really hope the bug *is* fixed. This has caused so many people so much work.

**Comment by janclarin** [comment] 2017-04-01 20:25
Thank you for all of your hard work!

**Comment by vitorgalvao** [comment] 2017-04-02 16:08
For anyone looking to update `alfred-workflow` on all their Workflows, this should suffice (don’t forget to change the first line):

```bash
cd "{{WHATEVER YOUR WORKFLOWS DIRECTORY IS}}"

IFS=$'\n'

for i in $(find . -name 'workflow.py'); do
  grep --quiet 'Dean Jackson <deanishe@deanishe.net>' "${i}" || continue
  pip install --target "$(dirname "${i}")" --upgrade Alfred-Workflow
done
```

Explanation:

+ Change the [internal field separator](https://en.wikipedia.org/wiki/Internal_field_separator) to just newlines, just in case.
+ Find all `workflow.py` files.
+ Make sure the file contains `Dean Jackson <deanishe@deanishe.net>` (so we know it’s not just some other `workflow.py`.
  + If it’s not the right one, restart the loop with the next one.
  + If it is the right one, update.

Now we just need to [get `--target` fixed in pip](https://github.com/pypa/pip/issues/4390). How I loathe `pip`; it never works reliably for me. Seriously one of the main reasons that always pushes me away from python.

Related: any other option we should/could use instead of `--target` with the same outcome, @deanishe?

**Comment by deanishe** [comment] 2017-04-02 16:35
WRT `pip --target`, I always use the following command, as the Homebrew Python/pip won't accept `--target` due to the above bug:

`/usr/bin/python -m pip install --target . Alfred-Workflow`

That uses the system Python, which works better with pip.

I have that (minus the package name) saved as an alias. Of course, it requires pip to be installed where the system Python can see it.

**Comment by deanishe** [comment] 2017-04-03 16:15
[This workflow](https://github.com/deanishe/alfred-fixum) should be able to fix any borked workflows a user has installed.

**Comment by deanishe** [comment] 2017-04-03 18:48
Also, I managed to track down [where I originally got the forking code from](http://code.activestate.com/recipes/66012/#c6). A Python Cookbook comment by (I think) @noahspurrier from almost 15 years ago.

And I've been using it for almost that long, too. Always worked flawlessly on Linux and OSX until bloody Sierra.

**Comment by vitorgalvao** [comment] 2017-04-03 19:31
> until bloody Sierra.

Until `10.12.4`, more precisely. That update also broke [shotcut](https://www.shotcut.org/) (crashed on launch). And [Ars Technica saying there wasn’t much to this update](https://arstechnica.com/apple/2017/03/macos-10-12-4-update-brings-night-shift-to-the-mac-and-not-much-else/). We beg to differ!

The amount of disruption this caused is a testament to how good and popular Alfred-Workflow is, though. Thank you for working on it, @deanishe.

**Comment by deanishe** [comment] 2017-04-03 21:04
> The amount of disruption this caused is a testament to how good and popular Alfred-Workflow is

Although it arguably says different things about the popularity and the goodness…

This is what you get for writing a library instead of a program, I guess. When something is broken, it doesn't only affect your own stuff.

Thanks for your fixer-upper script, btw, @vitorgalvao. I copied your method for the workflow version, just removing the dependency on pip.

**Comment by garyhesse** [comment] 2017-08-17 17:46
Ran Fixum to update the Wunderlist workflow (0.6.3); debug now shows this error when I attempt to call the workflow:
`[2017-08-17 10:43:53][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "alfred-wunderlist-workflow.py", line 21, in <module>
    sys.exit(wf.run(main, plaintext_exceptions='--commit' in wf.args))
TypeError: run() got an unexpected keyword argument 'plaintext_exceptions'`

**Comment by idpaterson** [comment] 2017-08-17 18:00
@garyhesse please report that on the Wunderlist workflow [over here](https://github.com/idpaterson/alfred-wunderlist-workflow) in case anyone else has that issue. I was using a fork of alfred-workflow that had an earlier version of a feature for showing exceptions, this should not be anything that affects other workflows via alfred-workflow.
